### ISSUE TITLE
Add feature to vendor openssl

### ISSUE THREAD

**Issue by tshepang** [malept/crypto-hash#17]
To help build more portable executables, it would be nice to have an option to build against a vendored openssl version.

At the moment, I have to do the following myself, even though openssl is a transitive dependency:
```toml
# This is a hack, to force openssl to be built statically.
# It's a dependency of crypto-hash.
[dependencies.openssl]
version = "0.10"
features = ["vendored"]
```
